name: Tests

on:
  push:
    paths:
      - "utils/**"
  pull_request:
    paths:
      - "utils/**"

jobs:
  run-unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: cd utils && yarn install --frozen-lockfile

      - name: Run tests
        run: cd utils && yarn test
